"""
Orchestrator Module

Main coordination script for the AI Employee system.
Triggers Claude Code to process pending items and update the dashboard.
"""

import subprocess
import sys
import logging
from pathlib import Path
from datetime import datetime
from typing import List, Tuple


class Orchestrator:
    """
    Orchestrates the AI Employee workflow.
    
    Responsibilities:
    1. Check for pending items in Needs_Action folder
    2. Trigger Qwen Code to process items
    3. Update Dashboard.md with current status
    4. Log all activities
    """
    
    def __init__(self, vault_path: str, qwen_code_command: str = 'qwen'):
        """
        Initialize the orchestrator.
        
        Args:
            vault_path: Path to the Obsidian vault root
            qwen_code_command: Command to run Qwen Code (default: 'qwen')
        """
        self.vault_path = Path(vault_path)
        self.needs_action = self.vault_path / 'Needs_Action'
        self.pending_approval = self.vault_path / 'Pending_Approval'
        self.approved = self.vault_path / 'Approved'
        self.done = self.vault_path / 'Done'
        self.logs = self.vault_path / 'Logs'
        self.dashboard = self.vault_path / 'Dashboard.md'
        self.plans = self.vault_path / 'Plans'
        
        # Ensure directories exist
        for folder in [self.needs_action, self.pending_approval, self.approved, 
                       self.done, self.logs, self.plans]:
            folder.mkdir(parents=True, exist_ok=True)
        
        self.qwen_command = qwen_code_command
        self._setup_logging()
        
    def _setup_logging(self):
        """Configure logging."""
        log_file = self.logs / f'orchestrator_{datetime.now().strftime("%Y-%m-%d")}.log'
        
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            handlers=[
                logging.FileHandler(log_file),
                logging.StreamHandler()
            ]
        )
        self.logger = logging.getLogger('Orchestrator')
    
    def count_pending_items(self) -> Tuple[int, int, int]:
        """
        Count items in different states.
        
        Returns:
            Tuple of (needs_action_count, pending_approval_count, approved_count)
        """
        na_count = len(list(self.needs_action.glob('*.md')))
        pa_count = len(list(self.pending_approval.glob('*.md')))
        approved_count = len(list(self.approved.glob('*.md')))
        
        return na_count, pa_count, approved_count
    
    def update_dashboard(self):
        """Update the Dashboard.md with current status."""
        na_count, pa_count, approved_count = self.count_pending_items()
        
        # Count today's completed items
        today = datetime.now().strftime('%Y-%m-%d')
        done_count = len(list(self.done.glob(f'*{today.replace("-", "")}*')))
        
        # Get recent activity from logs
        recent_activity = self._get_recent_activity()
        
        # Build dashboard content
        content = f'''---
last_updated: {datetime.now().isoformat()}
status: active
---

# AI Employee Dashboard

> **Status:** 🟢 Operational | **Mode:** Bronze Tier | **Last Activity:** Just now

---

## 📊 Quick Stats

| Metric | Value | Trend |
|--------|-------|-------|
| Pending Tasks | {na_count} | {"↑" if na_count > 0 else "-"} |
| Awaiting Approval | {pa_count} | {"↑" if pa_count > 0 else "-"} |
| Completed Today | {done_count} | - |
| Revenue MTD | $0 | - |

---

## 📥 Inbox Status

- **Inbox:** 0 items
- **Needs Action:** {na_count} items
- **In Progress:** 0 items
- **Pending Approval:** {pa_count} items

---

## ✅ Recent Activity

{recent_activity if recent_activity else '*No recent activity. Drop a file in `/Inbox` or `/Needs_Action` to get started.*'}

---

## 🎯 Active Projects

| Project | Status | Next Step |
|---------|--------|-----------|
| *None active* | - | - |

---

## ⚠️ Alerts & Notifications

{f'- **{pa_count} item(s) awaiting approval**' if pa_count > 0 else '- No active alerts'}

---

## 📝 Quick Commands

```bash
# Process all pending items
claude --cwd "D:\\FTE_AI_Employee\\AI_Employee_Vault"

# Run the orchestrator
python orchestrator.py

# Check watcher status
python filesystem_watcher.py
```

---

## 🔗 Quick Links

- [[Company_Handbook]] - Rules of engagement
- [[Business_Goals]] - Objectives and metrics
- [[Plans]] - Active task plans
- [[Logs]] - Activity logs

---

*Generated by AI Employee v0.1 (Bronze Tier)*
'''
        
        self.dashboard.write_text(content, encoding='utf-8')
        self.logger.info('Dashboard updated')
    
    def _get_recent_activity(self) -> str:
        """Get recent activity from log files."""
        try:
            # Read today's orchestrator log
            log_file = self.logs / f'orchestrator_{datetime.now().strftime("%Y-%m-%d")}.log'
            if log_file.exists():
                lines = log_file.read_text().split('\n')[-5:]  # Last 5 lines
                activities = []
                for line in lines:
                    if 'INFO' in line and 'Processed' in line:
                        # Extract meaningful info
                        parts = line.split(' - ')
                        if len(parts) > 3:
                            activities.append(f'- {parts[-1]}')
                
                if activities:
                    return '\n'.join(activities[-5:])
        except Exception as e:
            self.logger.debug(f'Could not get recent activity: {e}')
        
        return ''
    
    def process_pending_items(self, dry_run: bool = False):
        """
        Process all pending items using Claude Code.
        
        Args:
            dry_run: If True, log what would be done without executing
        """
        na_count, pa_count, approved_count = self.count_pending_items()
        
        self.logger.info(f'Starting processing run')
        self.logger.info(f'Needs Action: {na_count}, Pending Approval: {pa_count}, Approved: {approved_count}')
        
        if dry_run:
            self.logger.info('[DRY RUN] Would process items but dry_run=True')
            return
        
        # Check if there's anything to process
        if na_count == 0 and approved_count == 0:
            self.logger.info('No items to process')
            self.update_dashboard()
            return
        
        # Build the Qwen Code prompt
        prompt = self._build_prompt(na_count, pa_count, approved_count)

        # Run Qwen Code
        self.logger.info('Invoking Qwen Code...')
        try:
            # Use shell=True to ensure PATH is inherited correctly on Windows
            # Qwen Code uses -p for prompt, no --verbose flag needed
            result = subprocess.run(
                f'{self.qwen_command} -p "{prompt}"',
                cwd=str(self.vault_path),
                capture_output=True,
                text=True,
                timeout=300,  # 5 minute timeout
                shell=True,
                encoding='utf-8',
                errors='replace'
            )

            if result.returncode == 0:
                self.logger.info('Qwen Code processing completed successfully')
            else:
                self.logger.error(f'Qwen Code exited with code {result.returncode}')
                if result.stderr:
                    self.logger.error(f'Stderr: {result.stderr[:500]}')

        except subprocess.TimeoutExpired:
            self.logger.error('Qwen Code processing timed out (5 minutes)')
        except FileNotFoundError:
            self.logger.error(f'Qwen Code command not found: {self.qwen_command}')
            self.logger.error('Make sure Qwen Code is installed')
            self.logger.error('Try running: where qwen')
        except Exception as e:
            self.logger.error(f'Error running Qwen Code: {e}')
        
        # Update dashboard after processing
        self.update_dashboard()
    
    def _build_prompt(self, na_count: int, pa_count: int, approved_count: int) -> str:
        """
        Build the prompt for Qwen Code.
        
        Args:
            na_count: Number of items in Needs_Action
            pa_count: Number of items in Pending_Approval
            approved_count: Number of items in Approved
            
        Returns:
            Formatted prompt string
        """
        prompt = '''You are an AI Employee assistant. Process the pending items in this vault.

## Your Tasks:

1. **Review Needs_Action folder**: Read all .md files in /Needs_Action
2. **Create Plans**: For each item, create a Plan.md in /Plans with checkboxes for required steps
3. **Process Simple Items**: If an item can be completed in one step, do it and move to /Done
4. **Request Approval**: For sensitive actions (payments, external communications), create a file in /Pending_Approval
5. **Update Dashboard**: After processing, summarize what was done

## Rules:
- Always be polite and professional
- Flag anything over $500 for human approval
- Log all actions taken
- Move completed items to /Done
- If unsure, ask for clarification in the action file

## Current Status:
- Needs Action: ''' + str(na_count) + ''' items
- Pending Approval: ''' + str(pa_count) + ''' items
- Approved (ready to execute): ''' + str(approved_count) + ''' items

Start by reading the files in /Needs_Action and /Company_Handbook.md for context.
'''
        return prompt
    
    def run_once(self, dry_run: bool = False):
        """Run a single processing cycle."""
        self.process_pending_items(dry_run=dry_run)
    
    def run_continuous(self, interval: int = 60, dry_run: bool = False):
        """
        Run continuous processing cycles.
        
        Args:
            interval: Seconds between processing runs
            dry_run: If True, log without executing
        """
        import time
        
        self.logger.info(f'Starting continuous mode (interval: {interval}s)')
        
        try:
            while True:
                self.run_once(dry_run=dry_run)
                time.sleep(interval)
        except KeyboardInterrupt:
            self.logger.info('Continuous mode stopped by user')


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description='AI Employee Orchestrator')
    parser.add_argument(
        '--vault', '-v',
        default=r'D:\FTE_AI_Employee\AI_Employee_Vault',
        help='Path to Obsidian vault'
    )
    parser.add_argument(
        '--continuous', '-c',
        action='store_true',
        help='Run in continuous mode'
    )
    parser.add_argument(
        '--interval', '-i',
        type=int,
        default=60,
        help='Interval between runs in continuous mode (default: 60)'
    )
    parser.add_argument(
        '--dry-run', '-n',
        action='store_true',
        help='Log actions without executing'
    )
    parser.add_argument(
        '--qwen-cmd',
        default='qwen',
        help='Qwen Code command (default: qwen)'
    )
    
    args = parser.parse_args()
    
    orchestrator = Orchestrator(args.vault, args.qwen_cmd)
    
    if args.continuous:
        orchestrator.run_continuous(interval=args.interval, dry_run=args.dry_run)
    else:
        orchestrator.run_once(dry_run=args.dry_run)


if __name__ == '__main__':
    main()
